mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 33060
  database: charge
  charset: utf8mb4
  parseTime: true
  location: Asia%2FShanghai

http-server:
  host: 127.0.0.1
  port: 8888